import{a as h,S as w,i as a}from"./assets/vendor-xpOxgMII.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const L="https://pixabay.com/api/",b="54231751-132efb34a356b2aedfd75411f";async function y(r,s=1,e=15){return(await h.get(L,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:e}})).data}const f=document.querySelector(".gallery"),S=new w(".gallery a");function q(){f.innerHTML=""}function m(r){const s=r.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><span>Likes</span><span>${e.likes}</span></p>
          <p><span>Views</span><span>${e.views}</span></p>
          <p><span>Comments</span><span>${e.comments}</span></p>
          <p><span>Downloads</span><span>${e.downloads}</span></p>
        </div>
      </li>
      `).join("");f.insertAdjacentHTML("beforeend",s),S.refresh()}function g(){document.querySelector(".loader").classList.remove("is-hidden")}function u(){document.querySelector(".loader").classList.add("is-hidden")}const v=document.querySelector(".form"),i=document.querySelector(".load-more");let p="",n=1;const l=40;i.style.display="none";v.addEventListener("submit",async r=>{r.preventDefault();const s=r.target.elements["search-text"].value.trim();if(!s){a.warning({message:"Please enter a search query"});return}p=s,n=1,q(),i.style.display="none",g();try{const e=await y(p,n,l);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"}),u();return}n*l<e.totalHits&&(i.style.display="block"),m(e.hits)}catch(e){a.error({message:"Something went wrong. Please try again later."}),console.log(e)}finally{u()}});i.addEventListener("click",async()=>{n+=1,g();try{const r=await y(p,n,l);m(r.hits),n*l>=r.totalHits&&(i.style.display="none",a.info({message:"We're sorry, but you've reached the end of search results."}));const{height:s}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}catch(r){a.error({message:"Something went wrong. Please try again later."}),console.log(r)}finally{u()}});
//# sourceMappingURL=index.js.map
